### ISSUE TITLE
Weird colors in ST3, OS X, HiDPI

### ISSUE THREAD

**Issue by rik** [SalGnt/brackets-theme#3]
This is what I'm seeing after installing it with Package Control.
![screen shot 2013-08-23 at 10 16 04](https://f.cloud.github.com/assets/3653/1014959/7ae9d1b2-0bcc-11e3-8e53-fe7198196cfc.png)

**Comment by SalGnt** [comment]
My theme isn't available yet through Package Control, maybe you installed [this one](https://sublime.wbond.net/packages/Theme%20-%20Brackets) instead. Please install it manually following the instructions on `README` file.

**Comment by rik** [comment]
Ah right, sorry :)

**Comment by SalGnt** [comment]
No problem! :)
