### ISSUE TITLE
question about v scroll in sidebar

### ISSUE THREAD

**Issue by rootsical** [SalGnt/brackets-theme#4]
firstly thanks for sorting this theme out - very nice. just wondered, my vertical scrollbar isn't reaching to the top in the sidebar, there is an annoying little gap.. i think it would be better to go all the way to the top if poss. do you know how that could be achieved? thanks a lot..
![sublime-brackets-v-scroll-issue](https://f.cloud.github.com/assets/1428831/1425625/c91a8408-4042-11e3-916d-a4467774ec7a.png)

**Comment by l4ci** [comment]
Interesting, I think this comes because I changed the "padding" of the sidebar. Will look into that!

**Comment by rootsical** [comment]
thanks - works a treat!
