### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by jbrooksuk** [SalGnt/brackets-theme#9]
Am I ok submitting this to Package Control?

**Comment by SalGnt** [comment]
Yes, but there is a problem. A theme named _Brackets_ is already listed in Package Control.

**Comment by jbrooksuk** [comment]
There is, it's listed as ST2 only though, since I don't use ST2, do you know if it's an actual Brackets theme?

**Comment by SalGnt** [comment]
Yes, it's a Brackets theme.
